spring:
  sql:
    init:
      platform: postgresql
  datasource:
    url: jdbc:postgresql://ec2-34-253-116-145.eu-west-1.compute.amazonaws.com:5432/d3atqab1d7b6il
    username: kntjrtswcibime
    password: bd9fb6736bce53a15448bc2f3017335a0935176ae0bde64b0ef4b68f6a01149e
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
