spring:
  sql:
    init:
      platform: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/ONLINE_BANK
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
