version: '2.1'
services:
  application:
    container_name: online-bank
    image: app/online-bank:latest
    command: >
      java -jar bank-web.jar
    ports:
      - ${PORT:-8080}:8080
    depends_on:
      - online-bank-postgres
