version: '2.1'
services:
  arta-postgres:
    container_name: online-bank-postgres
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: ONLINE_BANK
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - ${PG_PORT:-5432}:5432
